name: asroo_store
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
<<<<<<< HEAD
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

=======
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
>>>>>>> div
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  very_good_analysis: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/play_store_512.png"

flutter:

  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - lang/ar.json
    - lang/en.json
    - assets/images/core/
    - assets/images/admin/
    - assets/images/customer/
    - assets/svg/

  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
