// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC54GFzEMG_qt7i_3PkoEo_fKZIdKFTpW8',
    appId: '1:183027169972:web:61428b863e1afc692535e1',
    messagingSenderId: '183027169972',
    projectId: 'asroostore-7fd13',
    authDomain: 'asroostore-7fd13.firebaseapp.com',
    storageBucket: 'asroostore-7fd13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2OHmBkJCLb4WBvoQBVpM__da5JNFJ87w',
    appId: '1:183027169972:android:936e0d2acbe7389a2535e1',
    messagingSenderId: '183027169972',
    projectId: 'asroostore-7fd13',
    storageBucket: 'asroostore-7fd13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30TdNgrfIo1Lb3gblCcBMRFQ8RIqTBtc',
    appId: '1:183027169972:ios:3acd97d329abdc922535e1',
    messagingSenderId: '183027169972',
    projectId: 'asroostore-7fd13',
    storageBucket: 'asroostore-7fd13.appspot.com',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30TdNgrfIo1Lb3gblCcBMRFQ8RIqTBtc',
    appId: '1:183027169972:ios:3acd97d329abdc922535e1',
    messagingSenderId: '183027169972',
    projectId: 'asroostore-7fd13',
    storageBucket: 'asroostore-7fd13.appspot.com',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC54GFzEMG_qt7i_3PkoEo_fKZIdKFTpW8',
    appId: '1:183027169972:web:3cc034eaea4ea8062535e1',
    messagingSenderId: '183027169972',
    projectId: 'asroostore-7fd13',
    authDomain: 'asroostore-7fd13.firebaseapp.com',
    storageBucket: 'asroostore-7fd13.appspot.com',
  );
}
